resume_from_checkpoint_path: null # only used for resume_from_checkpoint option in PL
result_path: "./result/SRFUND"
pretrained_model_name_or_path: "naver-clova-ix/donut-base" # loading a pre-trained model (from moldehub or path)
dataset_name_or_paths: ["../../Data/SRFUND/donut_format_sequenced"] # loading datasets (from moldehub or path)
sort_json_key: False # cord dataset is preprocessed, and publicly available at https://huggingface.co/datasets/naver-clova-ix/cord-v2
train_batch_sizes: [2]
val_batch_sizes: [1]
input_size: [960, 1280] # when the input resolution differs from the pre-training setting, some weights will be newly initialized (but the model training would be okay)
max_length: 512
align_long_axis: True
num_nodes: 1
seed: 123
lr: 2e-5
warmup_steps: 50 # 800/8*30/10, 10%
num_training_samples_per_epoch: 139
max_epochs: 10
max_steps: -1
num_workers: 8
val_check_interval: 1.0
check_val_every_n_epoch: 1
# Early stopping to prevent overfitting
early_stopping_patience: 3
save_top_k: 3
monitor_metric: "val_loss"
gradient_clip_val: 1.0
verbose: True
